services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    restart: always  # Faz o container subir junto com o Linux
    # ... resto das configurações
    ports:
      - '8080:8080'
    volumes:
      - ./trainingData:/usr/share/tessdata # Para OCR (opcional)
      - ./extraConfigs:/configs
      - ./logs:/logs
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false # Economiza RAM
      - LANGS=pt_BR
